### ISSUE TITLE
Passwords are currently in plaintext

### ISSUE THREAD

**Issue by RDilks** [yellow/alemania-tools#1]
**Describe the bug**
Currently the passwords are being stored in plaintext. We should store the hashed passwords instead for better security.

**Use Case involved**
Use Case 1

**Test Case involved**
TC - 003

**To Reproduce**
- Create an account.
- See plaintext password in the database.

**Expected behavior**
- Create an account
- See hashed password in the database.

**Additional context**
Created this issue as per our discussion.

**Comment by yellow** [comment]
Thanks. Will be working on this.

**Comment by yellow** [comment]
This issue has been fixed in 03e1b59. We currently use bcrypt to hash our passwords.
