### ISSUE TITLE
Tool Selection is accessible before being signed in

### ISSUE THREAD

**Issue by RDilks** [yellow/alemania-tools#3]
**Describe the bug**
I am able to access the Tool Selection page without needing to be signed in.

**Related Test Case**
TC-010

**To Reproduce**
Go to the home page while not being logged in.
The tool selection option will be displayed
When clicked on, it will bring the user regardless of their status of being registered or not to the tool selection page.

**Expected behavior**
When going to the home page while not being signed in, the tool selection page should not be accessible to users who are not signed in.

**Comment by yellow** [comment]
This has been fixed in the ad205aa commit.
Closing.
