### ISSUE TITLE
Unable to confirm term of service at check out

### ISSUE THREAD

**Issue by RDilks** [yellow/alemania-tools#4]
**Describe the bug**
No check box indicating that the user has to agree to terms of service

**Related Test Case**
TC-015

**To Reproduce**
1. Attempt to checkout an item while signed in
2. Scroll down to the bottom of the check out page
3. There is no checkout box available for the terms of service

**Expected behavior**
A terms of service button should be present and must be checked before a transaction can be processed.

**Comment by yellow** [comment]
04b8fa2 adds a ToS checkbox which needs to be checked before posting the repair request. Closing.
